# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0004_auto_20170221_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarschedule',
            name='event',
            field=models.CharField(choices=[('dawn_civil', 'dawn_civil'), ('dawn_astronomical', 'dawn_astronomical'), ('dawn_nautical', 'dawn_nautical'), ('dusk_nautical', 'dusk_nautical'), ('sunset', 'sunset'), ('sunrise', 'sunrise'), ('dusk_astronomical', 'dusk_astronomical'), ('solar_noon', 'solar_noon'), ('dusk_civil', 'dusk_civil')], max_length=24, verbose_name='event'),
        ),
    ]
